version: "3.3"

services:

  greenit-cli-influxdb:
    container_name: greenit-cli-influxdb
    image: ${INFLUXDB_IMAGE_VERSION}
    ports:
      - '8086:8086'
    volumes:
      - greenit-cli-influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB_NAME}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - greenit-cli-network

  greenit-cli-grafana:
    container_name: greenit-cli-grafana
    image: ${GRAFANA_IMAGE_VERSION}
    ports:
      - '3000:3000'
    volumes:
      - greenit-cli-grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - greenit-cli-influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    networks:
      - greenit-cli-network

volumes:
  greenit-cli-influxdb-storage:
    driver: local
  greenit-cli-grafana-storage:
    driver: local

networks:
  greenit-cli-network: